- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR adds the Issue Templates for bugs and feature request, and the information will help devs to replicate the issues with guided steps. thanks.
> Add issue templates for bug and feature.

- CHANGELOG.md
- package-lock.json
- package.json
These 2 files will make our workflow auto detect on a flow and create `release` and `publish` into market place. Thanks heaps and we can do a silent release for this one as folks have tested VSIX internally and all seemed in order.
Thanks, 🚀☕️ @hsubramanianaks , @qpetraroia , @sabbour , @elenavillamil , @gambtho
> Publish from gh workflow.

- CHANGELOG.md
Changelog entry had `[]` square bnracket missing, thanks cc: @hsubramanianaks
> fix changelog entry.

- CHANGELOG.md
- package-lock.json
- package.json
Moving release with manage identity and headless services fixes to production.
> Changelog and release

- CHANGELOG.md
- package-lock.json
- package.json
Last release for VSCode had wrong B2K CLI version in package.json, this PR is to correct it to avoid errors.
> Production Fix for wrong B2K CLI number

- README.md
Fixing svg scanning issue during publishing.
> Fix svg scanning issue nby removing the svg badges.

- CHANGELOG.md
Release is required. thanks, cc @hsubramanianaks 🥷🥷☕️
> Re-releasing with new version.

- CHANGELOG.md
- package-lock.json
- package.json
Update CLI version to include devshot agent port changes and json serialization changes.
> Jan 24 release

- CHANGELOG.md
- package-lock.json
- package.json
This change is to release vscode for B2K CLI changes, below is the change log for B2K. 
https://github.com/Azure/Bridge-To-Kubernetes/pull/225/files
> update changelog for 032923 release

- CHANGELOG.md
Change log had version mismatch, corrected it to right version.
> update to correct change log

- CHANGELOG.md
- package-lock.json
- package.json
This PR is to update B2K CLI to tested version with changelog for release.
> changelog for release 04.25

- README.md
following PR is minor fix to something which is currently appear out pf place in market place area.
Thanks heaps: cc: @hsubramanianaks 🙏❤️☕️
> Fix the link appearing out of place in VS Code marketplace.

- CHANGELOG.md
- package-lock.json
- package.json
This PR is for change log for 0530 release.
> Changelog for B2K CLI update release on May 30 2023

- README.md
This PR bubbles the latest codecov and build status. Essentially once merged it will be something like this.
Thank heaps, @peterbom, @hsubramanianaks ☕️❤️🥷
> Enable codecov and build badges for visibility.

- .github/workflows/publish.yml
This PR is to update node js version for publish workflow which was missed in the previous PR's.
> update publish workflow to use updated nodejs

- SUPPORT.md
Updated the doc support.md to match the B2k repo with proper links.
> Updated the support doc with correct links

- CHANGELOG.md
- package-lock.json
- package.json
This PR updates extension to use latest CLI version with multiple enhancements and fixes. Plus bug fixes and enhancements.
> update to latest b2k cli version for s360 fixes and other enhancements

- package-lock.json
- package.json
- src/ExtensionRoot.ts
- webpack.config.js
This PR is related to work item https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/24534129 
The package vscode-telementry-extension is deprecated, renaming it and updating the version.
https://www.npmjs.com/package/vscode-extension-telemetry?activeTab=versions
> Updated the telemetry extension

- CHANGELOG.md
- package-lock.json
- package.json
This PR is created to update the CLI version and changelog.md for releasing to the marketplace.
> Update the CLI version and changelog

- CHANGELOG.md
- package-lock.json
- package.json
This PR is to update change log with list of changes and update b2k cli version which has fixes for m1 mac issue and other dependent bot alert fixes.
> Jan 2024 release

- .github/workflows/build.yml
This PR is to fix build error for ubuntu and removes the codecov step due to rate limit error. 
Here is passing build - https://github.com/Azure/vscode-bridge-to-kubernetes/actions/runs/12204855605/job/34050857434
> fix build error
